//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldSkills_Client.Model.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Marathon
    {
        public byte MarathonId { get; set; }
        public string MarathonName { get; set; }
        public string CityName { get; set; }
        public string CountryCode { get; set; }
        public Nullable<short> YearHeld { get; set; }
    }
}
